AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ProjectSaes

  Sample SAM Template for ProjectSaes

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          RDS_SECRET_NAME: secretsSAES
          RDS_ENDPOINT: mydbinstance.abcde12345.us-east-1.rds.amazonaws.com
          RDS_DB_NAME: saesdb
          RDS_USERNAME: admin
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - rds-db:connect
              Resource: arn:aws:rds:us-east-1:654654356618:db:saesdb
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: arn:aws:kms:us-east-1:654654356618:key/3a580651-a429-4686-94c0-17a86fe6ac96
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: "*"
            - Effect: Allow
              Action:
                - apigateway:POST
                - apigateway:GET
                - apigateway:PUT
                - apigateway:DELETE
              Resource: "*"
            - Effect: Allow
              Action:
                - cognito-idp:AdminCreateUser
                - cognito-idp:AdminDeleteUser
                - cognito-idp:AdminGetUser
                - cognito-idp:AdminUpdateUserAttributes
              Resource: arn:aws:cognito-idp:us-east-1:654654356618:userpool/us-east-1_bUmZ4j6DU

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: saesusers
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: name
          Required: true
          Mutable: true
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: saesclient
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
